name: GitHub with FastGit
version: 1
description: 自动替换 GitHub 页面上的相关链接为 FastGit
include:
  - https://github.com/*
author: ShuangYa
run-at: document-end
icon: https://github.githubassets.com/favicons/favicon.png
grant:
  - unsafeWindow
namespace: blog.sylingd.com
