name: Akina
version: 2.0.4
description: 访问指定用户的百度网盘
include:
  - /https?:\/\/tieba\.baidu\.com\/p.*/
  - /https?:\/\/tieba\.baidu\.com\/f.*/
author: Paltoo Young
grant:
  - GM_xmlhttpRequest
namespace: http://tieba.baidu.com/f?kw=firefox
