name: GitHub Mirror
version: 1
description: 自动替换 GitHub 页面上的相关链接到镜像站
include:
  - https://github.com/*
author: ShuangYa
run-at: document-end
icon: https://github.githubassets.com/favicons/favicon.png
grant:
  - unsafeWindow
  - GM_registerMenuCommand
  - GM_setValue
  - GM_getValue
namespace: blog.sylingd.com
