name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build
        run: |
          npm run build-site
          node ./scripts/copy-master.js
      - name: Deploy master
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: dist/master
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/pages